name: Build Application and Deliver to Dockerhub

on:
  push:
    branches: [Dev]
  pull_request:
    branches: [Dev]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
      - name: get date
        id: date
        run: echo "::set-output name=date::$('%y-%m-%d')"
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Docker Image
        run: docker build -t shining118/galaxy-gaming-be:$date .
      - name: Push to Dockerhub
        run: docker push bpinkerton/quizlite:$date
