name: Build Application and Deliver to Dockerhub

on:
  push:
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Docker Image
        run: docker build -t shining118/galaxygamingbe:${{github.head_ref || github.ref_name}} .
      - name: Push to Dockerhub
        run: docker push shining118/galaxygamingbe:${{github.head_ref || github.ref_name}}
        
